"""EventStream - Temporal perception of game events.

Provides the agent's view of asynchronous game state changes.
This is the temporal complement to spatial views (ReachableView, RemoteView).

Agent Perception Model:
    Spatial (where things are):
        - ReachableView: nearby entities, mutable
        - RemoteView: map-wide via DuckDB, read-only

    Temporal (what's happening):
        - EventStream: game events over time

Events are generated by the Lua mod and sent via UDP. They include:
    - Research completions (unlocks new capabilities)
    - Crafting completions (for fire-and-forget NQ/DQ pattern)
    - Entity lifecycle events (future)
"""

from __future__ import annotations

import asyncio
import logging
import queue
from dataclasses import dataclass, field
from datetime import datetime
from typing import (
    Any,
    Awaitable,
    Callable,
    Dict,
    List,
    Optional,
    TYPE_CHECKING,
    TypeVar,
    Union,
)

if TYPE_CHECKING:
    from FactoryVerse.game.agent.infra.async_listener import AsyncActionListener

logger = logging.getLogger(__name__)

# Type for unsubscribe function
Unsubscribe = Callable[[], None]

# Event callback type
EventCallback = Callable[["GameEvent"], Awaitable[None]]

# Type variable for typed events
E = TypeVar("E", bound="GameEvent")


# =============================================================================
# Event Types
# =============================================================================


@dataclass
class GameEvent:
    """Base event from game.

    All game notifications are wrapped in this type for consistent handling.
    Subclasses provide typed access to event-specific data.

    Attributes:
        notification_type: Event type (e.g., "research_finished", "crafting_finished")
        agent_id: Numeric agent ID that received this event
        tick: Game tick when event occurred
        data: Event-specific payload
        timestamp: When Python received the event
    """
    notification_type: str
    agent_id: int
    tick: int
    data: Dict[str, Any]
    timestamp: datetime = field(default_factory=datetime.now)
    # Stream provenance (NOTIFICATIONS plan). None for events that did not
    # arrive on a sequenced stream.
    epoch: Optional[int] = None
    seq: Optional[int] = None
    source: Optional[str] = None
    filled_from_file: bool = False

    @property
    def is_critical(self) -> bool:
        """Whether this event significantly changes agent capabilities.

        Critical events may warrant immediate attention in the agent loop.
        """
        return self.notification_type in {
            "research_finished",   # New recipes/capabilities unlocked
            "crafting_finished",   # Items now available in inventory
        }

    def to_dict(self) -> Dict[str, Any]:
        """Return the stable wire representation used by coding harnesses."""
        out = {
            "notification_type": self.notification_type,
            "agent_id": self.agent_id,
            "tick": self.tick,
            "data": self.data,
            "critical": self.is_critical,
        }
        if self.seq is not None:
            out["epoch"] = self.epoch
            out["seq"] = self.seq
            out["source"] = self.source
            if self.filled_from_file:
                out["filled_from_file"] = True
        return out

    @classmethod
    def from_payload(cls, payload: Dict[str, Any]) -> "GameEvent":
        """Create appropriate event type from UDP payload.

        Dispatches to typed subclasses based on notification_type.
        """
        notification_type = payload.get("notification_type", "unknown")
        common = dict(
            notification_type=notification_type,
            agent_id=payload.get("agent_id", 0),
            tick=payload.get("tick", 0),
            data=payload.get("data", {}),
            epoch=payload.get("epoch"),
            seq=payload.get("seq"),
            source=payload.get("source"),
            filled_from_file=bool(payload.get("filled_from_file", False)),
        )

        # Dispatch to typed subclass — one branch per wire.turn name.
        if notification_type == "research_finished":
            return ResearchFinishedEvent(**common)
        elif notification_type == "research_started":
            return ResearchStartedEvent(**common)
        elif notification_type == "research_cancelled":
            return ResearchCancelledEvent(**common)
        elif notification_type == "research_queued":
            return ResearchQueuedEvent(**common)
        elif notification_type == "research_moved":
            return ResearchMovedEvent(**common)
        elif notification_type == "research_reversed":
            return ResearchReversedEvent(**common)
        elif notification_type == "crafting_finished":
            return CraftingFinishedEvent(**common)
        else:
            # Generic event for unknown types
            return cls(**common)


# =============================================================================
# Research Events
# =============================================================================


@dataclass
class ResearchFinishedEvent(GameEvent):
    """Research technology completed.

    This is a critical event - new recipes and capabilities are unlocked.
    The agent should re-evaluate its strategy when this occurs.
    """

    @property
    def technology(self) -> str:
        """Name of completed technology."""
        return self.data.get("technology", "unknown")

    @property
    def unlocked_recipes(self) -> List[str]:
        """Recipes unlocked by this technology."""
        return self.data.get("unlocked_recipes", [])

    @property
    def effects(self) -> List[Dict[str, Any]]:
        """Normalized technology effects applied at completion."""
        return self.data.get("effects", [])

    @property
    def level(self) -> Optional[int]:
        """Technology level (for infinite research)."""
        return self.data.get("level")

    def __str__(self) -> str:
        recipes = ", ".join(self.unlocked_recipes) if self.unlocked_recipes else "none"
        return f"Research Complete: {self.technology} (unlocked: {recipes})"


@dataclass
class ResearchStartedEvent(GameEvent):
    """Research technology started."""

    @property
    def technology(self) -> str:
        """Name of technology being researched."""
        return self.data.get("technology", "unknown")

    def __str__(self) -> str:
        return f"Research Started: {self.technology}"


@dataclass
class ResearchCancelledEvent(GameEvent):
    """Research cancelled."""

    @property
    def technologies(self) -> Dict[str, Any]:
        """Technologies that were cancelled."""
        return self.data.get("technologies", {})

    def __str__(self) -> str:
        techs = ", ".join(self.technologies.keys()) if self.technologies else "unknown"
        return f"Research Cancelled: {techs}"


@dataclass
class ResearchQueuedEvent(GameEvent):
    """Research added to queue."""

    @property
    def technology(self) -> str:
        """Name of queued technology."""
        return self.data.get("technology", "unknown")

    def __str__(self) -> str:
        return f"Research Queued: {self.technology}"


@dataclass
class ResearchMovedEvent(GameEvent):
    """Research queue reordered (force-scoped)."""

    def __str__(self) -> str:
        return "Research Queue Reordered"


@dataclass
class ResearchReversedEvent(GameEvent):
    """Research un-researched (force-scoped)."""

    @property
    def technology(self) -> str:
        return self.data.get("technology", "unknown")

    def __str__(self) -> str:
        return f"Research Reversed: {self.technology}"


# =============================================================================
# Crafting Events
# =============================================================================


@dataclass
class CraftingFinishedEvent(GameEvent):
    """Crafting completed (for fire-and-forget NQ/DQ pattern).

    This event is sent when crafting queued via the non-blocking pattern
    completes. It allows agents to craft items while doing other work
    and be notified when items are ready.

    Note: This is different from action completion for awaited crafts.
    """

    @property
    def recipe(self) -> str:
        """Recipe that was crafted."""
        return self.data.get("recipe", "unknown")

    @property
    def count(self) -> int:
        """Number of items crafted."""
        return self.data.get("count", 0)

    @property
    def action_id(self) -> Optional[str]:
        """Original action_id if linked."""
        return self.data.get("action_id")

    def __str__(self) -> str:
        return f"Crafting Complete: {self.recipe} x{self.count}"


# =============================================================================
# EventStream
# =============================================================================


class EventStream:
    """Temporal perception of game events.

    Provides the agent's view of asynchronous game state changes.
    Wraps Tier 3's notification queue with a clean, typed API.

    Usage:
        # Drain all pending events (non-blocking)
        events = await event_stream.drain()
        for event in events:
            if isinstance(event, ResearchFinishedEvent):
                print(f"New tech: {event.technology}")

        # Wait for specific event
        event = await event_stream.wait_for(
            "research_finished",
            predicate=lambda e: e.technology == "automation"
        )

        # Subscribe to event type
        def on_research(event):
            print(f"Research done: {event}")
        unsubscribe = event_stream.subscribe("research_finished", on_research)
    """

    def __init__(
        self,
        notification_queue: queue.Queue,
        listener: Optional["AsyncActionListener"] = None,
    ):
        """Initialize EventStream.

        Args:
            notification_queue: Thread-safe queue from AsyncActionListener
            listener: Optional reference to listener for callback registration
        """
        self._queue = notification_queue
        self._listener = listener
        self._subscriptions: Dict[str, List[EventCallback]] = {}
        self._running = True

    @property
    def pending_count(self) -> int:
        """Number of events waiting to be drained."""
        return self._queue.qsize()

    async def drain(self, timeout: float = 0.05) -> List[GameEvent]:
        """Get all pending events (non-blocking).

        Call this at strategic points in the agent loop to collect
        events that arrived since last drain.

        Args:
            timeout: Max time to wait for first event (seconds).
                    Use 0 for immediate return.

        Returns:
            List of GameEvent objects, possibly empty.
        """
        events: List[GameEvent] = []

        # Wait briefly for first event if timeout > 0
        if timeout > 0:
            try:
                # Non-blocking wait with small sleep intervals
                deadline = asyncio.get_event_loop().time() + timeout
                while asyncio.get_event_loop().time() < deadline:
                    try:
                        payload = self._queue.get_nowait()
                        event = GameEvent.from_payload(payload)
                        events.append(event)
                        await self._notify_subscribers(event)
                        break
                    except queue.Empty:
                        await asyncio.sleep(0.01)
            except Exception as e:
                logger.debug(f"EventStream drain error: {e}")

        # Drain remaining events (non-blocking)
        while True:
            try:
                payload = self._queue.get_nowait()
                event = GameEvent.from_payload(payload)
                events.append(event)
                await self._notify_subscribers(event)
            except queue.Empty:
                break

        if events:
            logger.debug(f"EventStream drained {len(events)} event(s)")

        return events

    async def wait_for(
        self,
        notification_type: str,
        predicate: Optional[Callable[[GameEvent], bool]] = None,
        timeout: Optional[float] = None,
    ) -> GameEvent:
        """Wait for a specific event.

        Useful for synchronization patterns where the agent needs to
        wait for a particular game state change.

        Args:
            notification_type: Event type to wait for (e.g., "research_finished")
            predicate: Optional filter function. Event must match this to be returned.
            timeout: Max wait time in seconds. None for indefinite wait.

        Returns:
            The matching GameEvent.

        Raises:
            asyncio.TimeoutError: If timeout expires before matching event.

        Example:
            # Wait for automation research to complete
            event = await events.wait_for(
                "research_finished",
                predicate=lambda e: e.data.get("technology") == "automation",
                timeout=300.0  # 5 minutes
            )
        """
        deadline = None
        if timeout is not None:
            deadline = asyncio.get_event_loop().time() + timeout

        # Buffer for non-matching events (re-queue them)
        buffered: List[Dict[str, Any]] = []

        try:
            while True:
                # Check timeout
                if deadline is not None:
                    remaining = deadline - asyncio.get_event_loop().time()
                    if remaining <= 0:
                        raise asyncio.TimeoutError(
                            f"Timeout waiting for {notification_type}"
                        )

                # Try to get event
                try:
                    payload = self._queue.get_nowait()
                    event = GameEvent.from_payload(payload)

                    # Check if this is the event we want
                    if event.notification_type == notification_type:
                        if predicate is None or predicate(event):
                            await self._notify_subscribers(event)
                            return event

                    # Not the event we want, buffer it
                    buffered.append(payload)

                except queue.Empty:
                    # No event available, wait a bit
                    await asyncio.sleep(0.05)

        finally:
            # Re-queue buffered events
            for payload in buffered:
                self._queue.put(payload)

    def subscribe(
        self,
        notification_type: str,
        callback: Union[Callable[[GameEvent], None], EventCallback],
    ) -> Unsubscribe:
        """Register callback for event type.

        The callback is invoked when events of the specified type are
        drained or waited for. This allows reactive handling of events.

        Args:
            notification_type: Event type to subscribe to (e.g., "research_finished")
                             Use "*" to subscribe to all events.
            callback: Function to call with the event. Can be sync or async.

        Returns:
            Unsubscribe function - call it to remove the subscription.

        Example:
            async def on_research(event):
                print(f"Research complete: {event.technology}")

            unsubscribe = events.subscribe("research_finished", on_research)
            # ... later ...
            unsubscribe()  # Stop receiving events
        """
        if notification_type not in self._subscriptions:
            self._subscriptions[notification_type] = []

        # Wrap sync callbacks
        if not asyncio.iscoroutinefunction(callback):
            original = callback
            async def async_wrapper(event: GameEvent) -> None:
                original(event)
            callback = async_wrapper

        self._subscriptions[notification_type].append(callback)

        def unsubscribe():
            if notification_type in self._subscriptions:
                try:
                    self._subscriptions[notification_type].remove(callback)
                except ValueError:
                    pass

        return unsubscribe

    async def _notify_subscribers(self, event: GameEvent) -> None:
        """Notify all subscribers of an event."""
        # Notify type-specific subscribers
        if event.notification_type in self._subscriptions:
            for callback in self._subscriptions[event.notification_type]:
                try:
                    await callback(event)
                except Exception as e:
                    logger.error(
                        f"Error in event subscriber for {event.notification_type}: {e}"
                    )

        # Notify wildcard subscribers
        if "*" in self._subscriptions:
            for callback in self._subscriptions["*"]:
                try:
                    await callback(event)
                except Exception as e:
                    logger.error(f"Error in wildcard event subscriber: {e}")

    def format_event(self, event: GameEvent) -> str:
        """Format event as human-readable string for LLM context.

        Args:
            event: Event to format

        Returns:
            Formatted string with emoji and details
        """
        tick_info = f"(tick {event.tick})"

        if isinstance(event, ResearchFinishedEvent):
            recipes = ", ".join(event.unlocked_recipes) if event.unlocked_recipes else "none"
            return f"🔬 **Research Complete**: {event.technology}\n   Unlocked recipes: {recipes} {tick_info}"

        elif isinstance(event, ResearchStartedEvent):
            return f"🔬 **Research Started**: {event.technology} {tick_info}"

        elif isinstance(event, ResearchCancelledEvent):
            techs = ", ".join(event.technologies.keys()) if event.technologies else "unknown"
            return f"🔬 **Research Cancelled**: {techs} {tick_info}"

        elif isinstance(event, ResearchQueuedEvent):
            return f"🔬 **Research Queued**: {event.technology} {tick_info}"

        elif isinstance(event, CraftingFinishedEvent):
            return f"🔧 **Crafting Complete**: {event.recipe} x{event.count} {tick_info}"

        else:
            # Generic formatting
            return f"📢 **{event.notification_type}**: {event.data} {tick_info}"

    def format_events(self, events: List[GameEvent]) -> str:
        """Format multiple events for LLM context.

        Args:
            events: List of events to format

        Returns:
            Combined formatted string, or empty string if no events
        """
        if not events:
            return ""

        formatted = [self.format_event(e) for e in events]
        return "\n\n".join(formatted)
