"""Task definitions package.

This package contains all task definitions organized by type.
The ALL_TASKS list is used by the TaskRegistry to load tasks.
"""

from .throughput_tasks import (
    THROUGHPUT_TASKS,
    list_throughput_tasks,
    get_throughput_task,
    # Task key constants
    ADVANCED_CIRCUIT_THROUGHPUT,
    AUTOMATION_SCIENCE_PACK_THROUGHPUT,
    BATTERY_THROUGHPUT,
    CHEMICAL_SCIENCE_PACK_THROUGHPUT,
    CRUDE_OIL_THROUGHPUT,
    ELECTRONIC_CIRCUIT_THROUGHPUT,
    ENGINE_UNIT_THROUGHPUT,
    INSERTER_THROUGHPUT,
    IRON_GEAR_WHEEL_THROUGHPUT,
    IRON_ORE_THROUGHPUT,
    IRON_PLATE_THROUGHPUT,
    LOGISTICS_SCIENCE_PACK_THROUGHPUT,
    LOW_DENSITY_STRUCTURE_THROUGHPUT,
    MILITARY_SCIENCE_PACK_THROUGHPUT,
    PETROLEUM_GAS_THROUGHPUT,
    PIERCING_ROUND_THROUGHPUT,
    PLASTIC_BAR_THROUGHPUT,
    PROCESSING_UNIT_THROUGHPUT,
    PRODUCTION_SCIENCE_PACK_THROUGHPUT,
    STEEL_PLATE_THROUGHPUT,
    STONE_WALL_THROUGHPUT,
    SULFURIC_ACID_THROUGHPUT,
    SULFUR_THROUGHPUT,
    UTILITY_SCIENCE_PACK_THROUGHPUT,
)
from .common import (
    LAB_STARTING_INVENTORY,
    MINIMAL_STARTING_INVENTORY,
    EMPTY_STARTING_INVENTORY,
)

# Aggregate all tasks for the registry
ALL_TASKS = list(THROUGHPUT_TASKS.values())

__all__ = [
    # Task collections
    "ALL_TASKS",
    "THROUGHPUT_TASKS",
    # Inventory configs
    "LAB_STARTING_INVENTORY",
    "MINIMAL_STARTING_INVENTORY",
    "EMPTY_STARTING_INVENTORY",
    # Functions
    "list_throughput_tasks",
    "get_throughput_task",
    # Task key constants
    "ADVANCED_CIRCUIT_THROUGHPUT",
    "AUTOMATION_SCIENCE_PACK_THROUGHPUT",
    "BATTERY_THROUGHPUT",
    "CHEMICAL_SCIENCE_PACK_THROUGHPUT",
    "CRUDE_OIL_THROUGHPUT",
    "ELECTRONIC_CIRCUIT_THROUGHPUT",
    "ENGINE_UNIT_THROUGHPUT",
    "INSERTER_THROUGHPUT",
    "IRON_GEAR_WHEEL_THROUGHPUT",
    "IRON_ORE_THROUGHPUT",
    "IRON_PLATE_THROUGHPUT",
    "LOGISTICS_SCIENCE_PACK_THROUGHPUT",
    "LOW_DENSITY_STRUCTURE_THROUGHPUT",
    "MILITARY_SCIENCE_PACK_THROUGHPUT",
    "PETROLEUM_GAS_THROUGHPUT",
    "PIERCING_ROUND_THROUGHPUT",
    "PLASTIC_BAR_THROUGHPUT",
    "PROCESSING_UNIT_THROUGHPUT",
    "PRODUCTION_SCIENCE_PACK_THROUGHPUT",
    "STEEL_PLATE_THROUGHPUT",
    "STONE_WALL_THROUGHPUT",
    "SULFURIC_ACID_THROUGHPUT",
    "SULFUR_THROUGHPUT",
    "UTILITY_SCIENCE_PACK_THROUGHPUT",
]
