"""File and directory management for agent sessions.

This module handles file-system concerns:
- Run directory creation and structure
- Session metadata persistence
- Path generation for session artifacts

Extracted from infra/llm/session_manager.py - that file can now import from here.
"""

import datetime
import json
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import Optional, Dict, Any, List


@dataclass
class SessionPaths:
    """File paths for a session's artifacts.

    Generated by FileManager.get_session_paths().
    """

    session_dir: Path
    metadata: Path
    notebook: Path
    chat_log: Path
    trajectory: Path
    initial_state: Path
    system_prompt: Path
    map_screenshot: Path

    def ensure_dir(self) -> None:
        """Ensure session directory exists."""
        self.session_dir.mkdir(parents=True, exist_ok=True)


@dataclass
class SessionConfig:
    """Configuration and metadata for an agent session.

    Tracks session identity, timing, and configuration.
    Persisted as metadata.json in session directory.
    """

    run_id: str
    model: str
    mode: str  # 'assisted' or 'autonomous'
    started_at: str
    provider: str = "unknown"  # LLM provider (e.g., 'prime_intellect', 'anthropic')
    ended_at: Optional[str] = None
    total_turns: int = 0
    config: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def create(
        cls,
        model: str,
        mode: str = "assisted",
        provider: str = "unknown",
        config: Optional[Dict[str, Any]] = None,
        run_id: Optional[str] = None,
    ) -> "SessionConfig":
        """Create a new session config with timestamp-based ID.

        Args:
            model: Model name (e.g., 'claude-3-opus', 'intellect-3')
            mode: 'assisted' or 'autonomous'
            provider: LLM provider (e.g., 'prime_intellect', 'anthropic')
            config: Optional additional configuration
            run_id: Optional explicit run ID (default: timestamp)

        Returns:
            New SessionConfig instance
        """
        if run_id is None:
            run_id = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

        return cls(
            run_id=run_id,
            model=model,
            mode=mode,
            provider=provider,
            started_at=datetime.datetime.now().isoformat(),
            config=config or {},
        )

    def mark_ended(self, total_turns: Optional[int] = None) -> None:
        """Mark session as ended.

        Args:
            total_turns: Final turn count
        """
        self.ended_at = datetime.datetime.now().isoformat()
        if total_turns is not None:
            self.total_turns = total_turns

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SessionConfig":
        """Create from dictionary."""
        return cls(**data)


class FileManager:
    """Manage agent session directories and metadata.

    Handles file-system organization for agent runs:
    - .fv-output/
      ├── runs/
      │   └── {model}/
      │       └── {run_id}/
      │           ├── metadata.json
      │           ├── notebook.ipynb
      │           ├── chat.md
      │           ├── trajectory.json
      │           └── ...
      └── config/

    This is a thin wrapper around file operations - it doesn't know
    about execution or domain concerns.
    """

    def __init__(self, output_dir: Optional[Path] = None):
        """Initialize file manager.

        Args:
            output_dir: Base output directory (default: .fv-output)
        """
        self.output_dir = Path(output_dir) if output_dir else Path(".fv-output")
        self.runs_dir = self.output_dir / "runs"
        self.config_dir = self.output_dir / "config"

    def initialize(self) -> None:
        """Create output directory structure."""
        self.runs_dir.mkdir(parents=True, exist_ok=True)
        self.config_dir.mkdir(parents=True, exist_ok=True)

    def get_session_dir(self, config: SessionConfig) -> Path:
        """Get session directory path.

        Directory structure: .fv-output/runs/{provider}/{model}/{run_id}/

        Args:
            config: Session configuration

        Returns:
            Path to session directory
        """
        return self.runs_dir / config.provider / config.model / config.run_id

    def get_session_paths(self, config: SessionConfig) -> SessionPaths:
        """Get all file paths for a session.

        Args:
            config: Session configuration

        Returns:
            SessionPaths with all artifact paths
        """
        session_dir = self.get_session_dir(config)

        return SessionPaths(
            session_dir=session_dir,
            metadata=session_dir / "metadata.json",
            notebook=session_dir / "notebook.ipynb",
            chat_log=session_dir / "chat.md",
            trajectory=session_dir / "trajectory.json",
            initial_state=session_dir / "initial_state.md",
            system_prompt=session_dir / "system_prompt.md",
            map_screenshot=session_dir / "map_overview.png",
        )

    def create_session(
        self,
        model: str,
        mode: str = "assisted",
        provider: str = "unknown",
        config: Optional[Dict[str, Any]] = None,
    ) -> SessionConfig:
        """Create new session with directory and metadata.

        Args:
            model: Model name
            mode: 'assisted' or 'autonomous'
            provider: LLM provider (e.g., 'prime_intellect', 'anthropic')
            config: Optional additional configuration

        Returns:
            New SessionConfig (directory created, metadata saved)
        """
        session_config = SessionConfig.create(
            model=model,
            mode=mode,
            provider=provider,
            config=config,
        )

        # Create directory
        session_dir = self.get_session_dir(session_config)
        session_dir.mkdir(parents=True, exist_ok=True)

        # Save metadata
        self.save_metadata(session_config)

        return session_config

    def save_metadata(self, config: SessionConfig) -> None:
        """Save session metadata to JSON.

        Args:
            config: Session configuration to save
        """
        paths = self.get_session_paths(config)
        paths.ensure_dir()

        with open(paths.metadata, "w") as f:
            json.dump(config.to_dict(), f, indent=2)

    def load_metadata(self, model: str, run_id: str) -> Optional[SessionConfig]:
        """Load session metadata from JSON.

        Args:
            model: Model name
            run_id: Run identifier

        Returns:
            SessionConfig if found, None otherwise
        """
        metadata_path = self.runs_dir / model / run_id / "metadata.json"

        if not metadata_path.exists():
            return None

        try:
            with open(metadata_path) as f:
                data = json.load(f)
            return SessionConfig.from_dict(data)
        except (json.JSONDecodeError, TypeError):
            return None

    def list_sessions(
        self,
        model: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> List[SessionConfig]:
        """List all sessions, optionally filtered by model.

        Recursively searches for metadata.json files to handle nested directory structures
        like provider/model/run_id or model/run_id.

        Args:
            model: Optional model name filter (matches SessionConfig.model field)
            limit: Maximum sessions to return

        Returns:
            List of SessionConfig, sorted by start time (newest first)
        """
        sessions = []

        if not self.runs_dir.exists():
            return []

        # Recursively find all metadata.json files
        for metadata_path in self.runs_dir.rglob("metadata.json"):
            # Extract model and run_id from path
            # Path structure: runs_dir / model / run_id / metadata.json
            # Or: runs_dir / provider / model / run_id / metadata.json
            try:
                # Get relative path from runs_dir
                rel_path = metadata_path.relative_to(self.runs_dir)
                parts = rel_path.parts
                
                # metadata.json is always the last part
                # So parts[:-1] gives us the directory path
                # Last part is run_id, second-to-last might be model or nested
                if len(parts) < 2:
                    continue  # Invalid structure
                
                run_id = parts[-2]  # Directory containing metadata.json
                
                # Model name is in the SessionConfig, so we need to load it to know
                # But we can also infer from path structure
                # Try loading first - it has the correct model name
                try:
                    with open(metadata_path) as f:
                        import json
                        data = json.load(f)
                        config = SessionConfig.from_dict(data)
                        
                        # Apply model filter if specified
                        if model and config.model != model:
                            continue
                            
                        sessions.append(config)
                except (json.JSONDecodeError, TypeError, KeyError):
                    # Skip invalid metadata files
                    continue
                    
            except (ValueError, IndexError):
                # Skip if path structure is unexpected
                continue

        # Sort newest first
        sessions.sort(key=lambda s: s.started_at, reverse=True)

        if limit:
            sessions = sessions[:limit]

        return sessions
